@echo off
echo Starting Nalderaone Studio Local Development Server...
echo ========================================================
echo Virtual environment: activating...
call .venv\Scripts\activate

echo Launching Background Task Process in a new window...
start cmd /k "title Nalderaone Worker && .venv\Scripts\activate && python manage.py process_tasks"

echo Launching Django Server...
python manage.py runserver 0.0.0.0:8000
